name: default
on: 
  push:
    branches:    
      - master
      - 'feature/**'
      - 'fix/**'
    paths-ignore:
      - README.md
    tags-ignore:
      - v*
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout repo
        uses: actions/checkout@v1
        
      - name: Tests
        run:  go test -v ./...